config/urls.py
"""
Настройка URL-адресов для проекта config.

Список `urlpatterns` перенаправляет URL-адреса в представления. Для получения дополнительной информации, пожалуйста, смотрите:
 https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
 1. Добавьте импорт: из my_app импортируйте представления
 2. Добавьте URL-адрес в urlpatterns: path(", views.home, name="home")
Представления на основе классов
 1. Добавьте импорт: из other_app.views импортируйте Home
 2. Добавьте URL-адрес в urlpatterns: path(", Home.as_view(), name="home")
Включая другой URLconf
 1. Импортируйте функцию include(): из django.urls импортируйте include, path
 2. Добавьте URL-адрес в urlpatterns: path('blog/', include('blog.urls'))
"""
"""Отслеживание url-адресов"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# urls для административной панели Django
urlpatterns = [
                  path('admin_panel/', admin.site.urls),  # URL для административной панели Django
                  path('', include('users.urls', namespace='users')),  # URL для приложения users
                  path('technic/', include('technic.urls', namespace='technic')), # URL для приложения technic
                  path('news/', include('news.urls', namespace='news')), # URL для приложения news
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавляем медиафайлы

news/urls.py
from django.urls import path

from news.apps import NewsConfig
from news.views import NewsListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = NewsConfig.name

urlpatterns = [
    path('', NewsListView.as_view(), name="news_list"),  # список всех новостей
    path('<int:pk>',ArticleDetailView.as_view(), name="news_detail"), # статья
    path('create/',ArticleCreateView.as_view(), name="news_create"), # создание статьи
    path('update/<int:pk>/',ArticleUpdateView.as_view(), name="news_update"), # редактирование статьи
    path('delete/<int:pk>',ArticleDeleteView.as_view(), name="news_delete"), # удаление статьи
]

news/models.py
from django.db import models

# настройка полей, чтобы возможно было заполнить поля пустыми
from users.models import NULLABLE

class Article(models.Model):
    """Статья"""
    title = models.CharField(max_length=100, verbose_name='Название', **NULLABLE)  # `Название новости
    description = models.CharField(max_length=250, verbose_name='Описание', **NULLABLE)  # Описание
    date = models.DateTimeField(verbose_name='Дата публикации')
    text = models.TextField(verbose_name="Текст статьи")


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

news/forms.py
from django import forms

from news.models import Article


class ArticleForm(forms.ModelForm):
    """ Форма статьи."""

    class Meta:
        model = Article
        fields = ['title', 'description', 'text']
        widgets = {
            'description': forms.Textarea(attrs={
                'cols': 65, 'rows': 5,
                'class': 'text_article_form'}),
            'text': forms.Textarea(attrs={
                # 'cols': 65, 'rows': 20,
                'class': 'text_article_form'}),
        }

news/views.py
from datetime import datetime

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from news.forms import ArticleForm
from news.models import Article


class NewsListView(ListView):
    """Список всех статей"""
    model = Article
    paginate_by = 5
    queryset = Article.objects.order_by('-date')
    template_name = 'news/news_list.html'
    extra_context = {
        'title': f'Новости'
    }


class ArticleDetailView(DetailView):
    """ Детальный просмотр статьи"""
    model = Article
    template_name = 'news/news_detail.html'

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        contex_data['title'] = f'{self.object.title}'
        return contex_data


class ArticleCreateView(CreateView):
    """ Создание техники"""
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('news:news_list')
    template_name = 'news/news_create.html'
    extra_context = {
        'title': f'Добавление статьи'
    }

    def form_valid(self, form):
        form.instance.date = datetime.now()  # assuming you want the current login user to be set to the user
        return super(ArticleCreateView, self).form_valid(form)


class ArticleUpdateView(UpdateView):
    """ Изменение статьи."""
    model = Article
    form_class = ArticleForm
    template_name = 'news/news_create.html'
    success_url = reverse_lazy('news:news_list')

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        if self.object:
            # если объект есть, тогда вписываем первый
            article_name = self.object.title
            contex_data['title'] = f'Редактирование статьи {article_name}'
        else:
            contex_data['title'] = f'Нет статьи'
        return contex_data


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    """ Удаление статьи"""
    model = Article
    template_name = 'news/news_delete.html'
    success_url = reverse_lazy('news:news_list')
    permission_required = 'news.delete_news'
    extra_context = {
        'title': f'Удаление статьи'
    }

news/templates/news/news_create.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'news:news_list' %}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

news/templates/news/news_delete.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                Вы хотите удалить статью: {{ object.title}}?
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Удаление</button>
                <a href="{% url 'news:news_list'%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

news/templates/news/news_detail.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
{% comment %} <div class="conteiner">
<div class="content_form">
    <button onclick="window.history.back(); return false;" class="btn_esc">Назад</button>
    <div class='block_data_news'>
    <div class="header_form heder_article">{{ title }} </div>
    <div class="date_article">{{ object.date }}</div>
    <div class="text_article">{{ object.text }}</div>
    
    
    <div class="btn_block_technic ">
        {% if request.user.role == "admin" or request.user.role == "moderator" %}
        <a class="btn_list btn_news" href="{% url 'news:news_update' object.pk %}">Редактирование</a>
        <a class="btn_list_delete btn_news" href="{% url 'news:news_delete' object.pk %}">Удаление</a>
        {% endif %}
    </div>

</div>
{% comment %} </div> {% endcomment %}
<div class="content_form">
    <button onclick="window.history.back(); return false;" class="btn_esc">Назад</button>
    <div class='block_data_news'>
        <div class="header_form heder_article">{{ title }} </div>
        <div class="date_article">{{ object.date }}</div>
        <div class="text_article">{{ object.text }}</div>
        <div class="btn_block_technic">
            {% if request.user.role == "admin" or request.user.role == "moderator" %}
            <a class="btn_list btn_article" href="{% url 'news:news_update' object.pk %}">Редактирование</a>
            <a class="btn_list_delete btn_article" href="{% url 'news:news_delete' object.pk %}">Удаление</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

news/templates/news/news_list.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    {% if request.user.role == "admin" or request.user.role == "moderator" %}
    <div class="top_bottom_list">
        <a href="{% url "news:news_create" %}" class="btn_list btn_list_high">Добавить новость</a>
    </div>
    {% endif %}
    <div class="conteiner_list_technic">
        {% for object in object_list %}
        {% include 'news/includes/inc_news_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'users/includes/inc_pagination.html' %}
</div>
{% endblock %}