config/urls.py
"""
Настройка URL-адресов для проекта config.

Список `urlpatterns` перенаправляет URL-адреса в представления. Для получения дополнительной информации, пожалуйста, смотрите:
 https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
 1. Добавьте импорт: из my_app импортируйте представления
 2. Добавьте URL-адрес в urlpatterns: path(", views.home, name="home")
Представления на основе классов
 1. Добавьте импорт: из other_app.views импортируйте Home
 2. Добавьте URL-адрес в urlpatterns: path(", Home.as_view(), name="home")
Включая другой URLconf
 1. Импортируйте функцию include(): из django.urls импортируйте include, path
 2. Добавьте URL-адрес в urlpatterns: path('blog/', include('blog.urls'))
"""
"""Отслеживание url-адресов"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# urls для административной панели Django
urlpatterns = [
                  path('admin_panel/', admin.site.urls),  # URL для административной панели Django
                  path('', include('users.urls', namespace='users')),  # URL для приложения users
                  path('technic/', include('technic.urls', namespace='technic')), # URL для приложения technic
                  path('news/', include('news.urls', namespace='news')), # URL для приложения news
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавляем медиафайлы

news/urls.py
from django.urls import path

from news.apps import NewsConfig
from news.views import NewsListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = NewsConfig.name

urlpatterns = [
    path('', NewsListView.as_view(), name="news_list"),  # список всех новостей
    path('<int:pk>',ArticleDetailView.as_view(), name="news_detail"), # статья
    path('create/',ArticleCreateView.as_view(), name="news_create"), # создание статьи
    path('update/<int:pk>/',ArticleUpdateView.as_view(), name="news_update"), # редактирование статьи
    path('delete/<int:pk>',ArticleDeleteView.as_view(), name="news_delete"), # удаление статьи
]

technic/urls.py
from django.urls import path

from technic.apps import TechnicConfig
from technic.views import TechnicListView, DepartmentListView, TypeListView, TypeTechnicUpdateView, \
    DepartmentUpdateView, TypeTechnicDeleteView, DepartmentDeleteView, DepartmentCreateView, TypeTechnicCreateView, \
    TechnicDetailView, TechnicUpdateView, TechnicDeleteView, TechnicCreateView, TechnicListFilterDepartmentView, \
    TechnicListFilterTypeTechnicView, TechnicSearchListView, TechnicServiceUpdateView, ServiceFilterTechnicView, \
    TechnicLostDataView

app_name = TechnicConfig.name

urlpatterns = [
    path('list/', TechnicListView.as_view(), name="technic_list"),  # список всей техники
    path('department/<int:pk>/technic/', TechnicListFilterDepartmentView.as_view(), name='department_technic'), # техника определенного подразделения
    path('type/<int:pk>/technic/', TechnicListFilterTypeTechnicView.as_view(), name='type_technic'), # техника определенного типа
    path('create/', TechnicCreateView.as_view(), name="technic_create"),  # добавление техники
    path('detail/<int:pk>/', TechnicDetailView.as_view(), name="technic_detail"),  # детальная информация по техники
    path('update/<int:pk>/', TechnicUpdateView.as_view(), name="technic_update"),  # редактирование техники
    path('delete/<int:pk>/', TechnicDeleteView.as_view(), name="technic_delete"),  # удаление техники
    path('type/', TypeListView.as_view(), name="type_list"),  # список всех типов техники
    path('department/', DepartmentListView.as_view(), name="department_list"),  # список всех подразделений
    path('type/create/', TypeTechnicCreateView.as_view(), name='type_create'), # создание типов техники
    path('department/create/', DepartmentCreateView.as_view(), name='department_create'), # создание подразделений
    path('type/update/<int:pk>/', TypeTechnicUpdateView.as_view(), name='type_update'), # редактирование типа техники
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'), # редактирование подразделений
    path('type/delete/<int:pk>/', TypeTechnicDeleteView.as_view(), name='type_delete'), # удаление типа техники
    path('department/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'), # удаление подразделений
    path('number/search/', TechnicSearchListView.as_view(), name='technic_search'), # поиск техники по гос номеру
    path('service/<int:pk>/', TechnicServiceUpdateView.as_view(), name='technic_service_update'), # сервис техники
    path('<int:pk>/service/', ServiceFilterTechnicView.as_view(), name='technic_service_list'), # список сервисов по техники
    path('<int:pk>/lost_data/', TechnicLostDataView.as_view(), name='technic_lost_data'), # последние данные от техники
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_login_view, user_logout_view, UserUpdateView, UserPasswordChangeView, UserProfileView, \
    UserListView, AllUserProfileView, ALLUserUpdateView, UserDeleteView, UserCreateView

app_name = UsersConfig.name

urlpatterns = [
    path('', user_login_view, name="login_user"), #  url стартовой страницы для входа
    path('logout/', user_logout_view, name="logout_user"),
    path('profile/', UserProfileView.as_view(), name='profile_user'),
    path('update/', UserUpdateView.as_view(), name="update_user"),
    path('change_password/', UserPasswordChangeView.as_view(), name='change_password_user'),

# просмотр других пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('create/', UserCreateView.as_view(), name='create_user'),
    path('profile/<int:pk>/', AllUserProfileView.as_view(), name='profile_all_user'),
    path('update/<int:pk>/', ALLUserUpdateView.as_view(), name='update_all_user'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='delete_user'),
]

users/models.py
# Описание моделей
from django.db import models
from django.contrib.auth.models import  AbstractUser
from django.utils.translation import gettext_lazy as _

# настройка полей, чтобы возможно было заполнить поля пустыми
NULLABLE ={'blank': True, 'null': True}

class UserRoles(models.TextChoices):
    """ Роли пользователь """
    ADMIN = 'admin', _('Администратор')
    MODERATOR = 'moderator', _('Модератор')
    USER = 'user', _('Пользователь')

class User(AbstractUser):
    """Модель пользователя с полями email, телефон и Telegram username."""
    username = None
    email = models.EmailField(unique=True,verbose_name='E-mail')
    role = models.CharField(max_length=9, choices=UserRoles.choices, default=UserRoles.USER)
    first_name = models.CharField(max_length=150, verbose_name='Имя',default="Не указано")
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', default="Не указано")
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    telegram = models.CharField(max_length=150, verbose_name='Телеграм', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватарка', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='active', help_text='Активный пользователь')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return  f'{self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural ='Пользователи'
        ordering = ['id']

users/forms.py
from django import forms
from .models import User

from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm

from users.validators import validate_password


class UserLoginForm(forms.Form):
    """ Форма для авторизации пользователя."""
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'class': 'input_login',
        'placeholder': 'Почта'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'input_login',
        'placeholder': 'Пароль'
    }))


class UserForm(forms.ModelForm):
    """ Форма пользователя."""

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',
                  'phone', 'telegram', 'avatar', 'role', 'is_active',)


class UserCreateForm(UserCreationForm):
    """ Форма для создания нового пользователя."""

    class Meta:
        # Поля модели User
        model = User
        fields = ('email', 'first_name', 'last_name',
                  'phone', 'telegram', 'role',)


class UserPasswordChangeForm(PasswordChangeForm):
    """ Форма для смены пароля."""

    def clean_new_password2(self):
        # Проверка соответствия паролей
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        password_validation.validate_password(password2, self.user)
        return password2

users/views.py
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import reverse, render, redirect

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

from django.urls import reverse_lazy
from django.views.generic import UpdateView, DetailView, ListView, DeleteView, CreateView

from users.forms import UserLoginForm, UserForm, UserPasswordChangeForm, UserCreateForm
from users.models import User


def user_login_view(request):
    # Выводим форму логина
    confirmation = True
    if request.method == 'POST':
        form = UserLoginForm(request.POST)  # Создаем экземпляр формы
        print(form.is_valid(), 'валидность')
        print(form.errors)
        if form.is_valid():  # Если форма валидна
            cd = form.cleaned_data  # Получаем данные email и password и очищаем форму
            user = authenticate(email=cd['email'], password=cd['password'])  # Аутентифицируем пользователя
            if user is not None:  # Если пользователь существует
                if user.is_active:  # Если пользователь активен
                    login(request, user)  # Авторизуем пользователя
                    return HttpResponseRedirect(
                        reverse('news:news_list'))  # Переход на страницу с новостями
                else:
                    return HttpResponse('Аккаунт не активен')
            else:
                confirmation = False

    form = UserLoginForm()
    context = {
        'form': form,
        'user': confirmation}
    return render(request, 'users/user_login.html', context)


def user_logout_view(request):
    # выход из системы
    print("выход из системы")
    logout(request)
    return redirect('users:login_user')


class UserCreateView(CreateView):
    """ Создание пользователя."""
    model = User
    form_class = UserCreateForm
    success_url = reverse_lazy('users:users_list')
    template_name = 'users/user_create.html'
    extra_context = {
        'title': f'Добавление пользователя'
    }


class UserProfileView(DetailView):
    """ Просмотр профиля пользователя."""
    model = User
    # form_class = UserForm
    template_name = 'users/user_profile.html'
    extra_context = {
        'title': f'Профиль пользователя'
    }

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(UpdateView):
    """ Изменение профиля пользователя."""
    model = User
    form_class = UserForm
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users:profile_user')
    extra_context = {
        'title': f'Редактирование профиля'
    }

    def get_object(self, queryset=None):
        # Получаем пользователя
        return self.request.user


class UserPasswordChangeView(PasswordChangeView):
    """ Изменение пароля пользователя."""
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('technic:technic_list')
    extra_context = {
        'title': f'Редактирование пароля'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = User.objects.get(pk=self.request.user.id)
        context["object.pk"] = obj.id
        return context


# Для работы с остальными пользователями (для админа)
class UserListView(LoginRequiredMixin, ListView):
    """ Список всех пользователей."""
    model = User
    paginate_by = 6
    template_name = 'users/users_all.html'
    extra_context = {
        'title': f'Все пользователи'
    }


class AllUserProfileView(DetailView):
    """ Просмотр профиля других пользователей."""
    model = User
    template_name = 'users/user_profile_all.html'
    extra_context = {
        'title': f'Профиль пользователя'
    }


class ALLUserUpdateView(UpdateView):
    """ Изменение профиля других пользователей."""
    model = User
    form_class = UserForm
    template_name = 'users/user_update_all.html'
    extra_context = {
        'title': f'Редактирование профиля'
    }

    def get_success_url(self):
        # Переходим на страницу детальной информацию пользователя после редактирования
        return reverse('users:profile_all_user', args=[self.kwargs.get('pk')])


class UserDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления пользователя."""
    model = User
    template_name = 'users/user_delete.html'
    # Переходим на страницу со списком питомцев после удаления
    success_url = reverse_lazy('users:users_list')
    permission_required = 'users.delete_user'
    extra_context = {
        'title': f'Удаление пользователя'
    }

users/templates/users/password_change.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Изменить</button>
                <a href="{% url 'users:profile_user' %}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/update_all_user.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'users:profile_all_user' object.pk %}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/update_user.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'users:profile_user'%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_create.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'users:users_list' %}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_delete.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                Вы хотите удалить пользователя {{ object.first_name}} {{ object.last_name}}
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Удаление</button>
                <a href="{% url 'users:users_list'%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'image/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="{% static 'css/login_page.css' %}" rel="stylesheet"/>
    <title>Control & Accounting system</title>
</head>
<body>
<div class="conteiner">
    <div class="block_left">
        <div class="logo">
            <img src="{% static 'image/logo.png' %}" alt="Система контроля и учета" style="width: auto;"/>
            <div class="text_logo">Система контроля и учета</div>
        </div>

        <div class="input">
            <form method="post" class="input_form">
                <div class="login_entet_text">Вход в систему:</div>
                <div class="input_form_box">
                    {% csrf_token %}
                    {{ form.email }}
                    {{ form.password }}
                    <button type="submit">Войти</button>
                </div>
                {% if user is False %}
                    <span style="color:red">Данные не корректны</span>
                {% endif %}
            </form>
        </div>
        <div class="footer">
            <div align="center">
                &#9733; This is my private "PET-project". Welcome my <a href="https://github.com/Zheldakov"
                                                                        target="_blank">github</a> page.
            </div>
        </div>
    </div>
    <div class="block_right">
        <div class="right_top_block">
            <div id="block_top"></div>
        </div>
        <div class="right_centr_block">
            <div id="block_center"></div>
        </div>
        <div class="right_bottom_block">
            <div id="block_bottom"></div>
        </div>
    </div>
</div>
</body>
</html>

users/templates/users/user_profile.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">{% include 'users/includes/inc_user_profile.html' with object=object %}
        <div class="button_form">
            <a href="{% url 'users:update_user' %}" class="btn_enter">Редактировать</a>
            <a href="{% url 'technic:technic_list' %}" class="btn_esc">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_profile_all.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
       {% include 'users/includes/inc_user_profile.html' with object=object %}
        <div class="button_form">
            <a href="{% url 'users:update_all_user' object.pk %}" class="btn_enter">Редактировать</a>
            <a href="{% url 'users:users_list' %}" class="btn_esc">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_update.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'users:profile_user'%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_update_all.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'users:profile_all_user' object.pk %}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/users_all.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <a href="{% url "users:create_user" %}" class="btn_list btn_list_high">Создать пользователя</a>
    <div class="conteiner_list">
        {% for object in object_list %}
        {% include 'users/includes/inc_user_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'users/includes/inc_pagination.html' %}
</div>
{% endblock %}