config/urls.py
"""
Настройка URL-адресов для проекта config.

Список `urlpatterns` перенаправляет URL-адреса в представления. Для получения дополнительной информации, пожалуйста, смотрите:
 https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
 1. Добавьте импорт: из my_app импортируйте представления
 2. Добавьте URL-адрес в urlpatterns: path(", views.home, name="home")
Представления на основе классов
 1. Добавьте импорт: из other_app.views импортируйте Home
 2. Добавьте URL-адрес в urlpatterns: path(", Home.as_view(), name="home")
Включая другой URLconf
 1. Импортируйте функцию include(): из django.urls импортируйте include, path
 2. Добавьте URL-адрес в urlpatterns: path('blog/', include('blog.urls'))
"""
"""Отслеживание url-адресов"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# urls для административной панели Django
urlpatterns = [
                  path('admin_panel/', admin.site.urls),  # URL для административной панели Django
                  path('', include('users.urls', namespace='users')),  # URL для приложения users
                  path('technic/', include('technic.urls', namespace='technic')), # URL для приложения technic
                  path('news/', include('news.urls', namespace='news')), # URL для приложения news
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавляем медиафайлы

news/urls.py
from django.urls import path

from news.apps import NewsConfig
from news.views import NewsListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = NewsConfig.name

urlpatterns = [
    path('', NewsListView.as_view(), name="news_list"),  # список всех новостей
    path('<int:pk>',ArticleDetailView.as_view(), name="news_detail"), # статья
    path('create/',ArticleCreateView.as_view(), name="news_create"), # создание статьи
    path('update/<int:pk>/',ArticleUpdateView.as_view(), name="news_update"), # редактирование статьи
    path('delete/<int:pk>',ArticleDeleteView.as_view(), name="news_delete"), # удаление статьи
]

technic/urls.py
from django.urls import path

from technic.apps import TechnicConfig
from technic.views import TechnicListView, DepartmentListView, TypeListView, TypeTechnicUpdateView, \
    DepartmentUpdateView, TypeTechnicDeleteView, DepartmentDeleteView, DepartmentCreateView, TypeTechnicCreateView, \
    TechnicDetailView, TechnicUpdateView, TechnicDeleteView, TechnicCreateView, TechnicListFilterDepartmentView, \
    TechnicListFilterTypeTechnicView, TechnicSearchListView, TechnicServiceUpdateView, ServiceFilterTechnicView, \
    TechnicLostDataView

app_name = TechnicConfig.name

urlpatterns = [
    path('list/', TechnicListView.as_view(), name="technic_list"),  # список всей техники
    path('department/<int:pk>/technic/', TechnicListFilterDepartmentView.as_view(), name='department_technic'), # техника определенного подразделения
    path('type/<int:pk>/technic/', TechnicListFilterTypeTechnicView.as_view(), name='type_technic'), # техника определенного типа
    path('create/', TechnicCreateView.as_view(), name="technic_create"),  # добавление техники
    path('detail/<int:pk>/', TechnicDetailView.as_view(), name="technic_detail"),  # детальная информация по техники
    path('update/<int:pk>/', TechnicUpdateView.as_view(), name="technic_update"),  # редактирование техники
    path('delete/<int:pk>/', TechnicDeleteView.as_view(), name="technic_delete"),  # удаление техники
    path('type/', TypeListView.as_view(), name="type_list"),  # список всех типов техники
    path('department/', DepartmentListView.as_view(), name="department_list"),  # список всех подразделений
    path('type/create/', TypeTechnicCreateView.as_view(), name='type_create'), # создание типов техники
    path('department/create/', DepartmentCreateView.as_view(), name='department_create'), # создание подразделений
    path('type/update/<int:pk>/', TypeTechnicUpdateView.as_view(), name='type_update'), # редактирование типа техники
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'), # редактирование подразделений
    path('type/delete/<int:pk>/', TypeTechnicDeleteView.as_view(), name='type_delete'), # удаление типа техники
    path('department/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'), # удаление подразделений
    path('number/search/', TechnicSearchListView.as_view(), name='technic_search'), # поиск техники по гос номеру
    path('service/<int:pk>/', TechnicServiceUpdateView.as_view(), name='technic_service_update'), # сервис техники
    path('<int:pk>/service/', ServiceFilterTechnicView.as_view(), name='technic_service_list'), # список сервисов по техники
    path('<int:pk>/lost_data/', TechnicLostDataView.as_view(), name='technic_lost_data'), # последние данные от техники
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_login_view, user_logout_view, UserUpdateView, UserPasswordChangeView, UserProfileView, \
    UserListView, AllUserProfileView, ALLUserUpdateView, UserDeleteView, UserCreateView

app_name = UsersConfig.name

urlpatterns = [
    path('', user_login_view, name="login_user"), #  url стартовой страницы для входа
    path('logout/', user_logout_view, name="logout_user"),
    path('profile/', UserProfileView.as_view(), name='profile_user'),
    path('update/', UserUpdateView.as_view(), name="update_user"),
    path('change_password/', UserPasswordChangeView.as_view(), name='change_password_user'),

# просмотр других пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('create/', UserCreateView.as_view(), name='create_user'),
    path('profile/<int:pk>/', AllUserProfileView.as_view(), name='profile_all_user'),
    path('update/<int:pk>/', ALLUserUpdateView.as_view(), name='update_all_user'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='delete_user'),
]

technic/forms.py
from django import forms
from .models import Department, TypeTechnic, Technic, Service


class DepartmentForm(forms.ModelForm):
    """ Форма подразделения."""

    class Meta:
        model = Department
        fields = '__all__'

        widgets = {
            'description': forms.Textarea(attrs={
                'cols': 65, 'rows': 5,
                'class': 'text_article_form'}),
        }


class TypeTechnicForm(forms.ModelForm):
    """ Форма типа техники"""

    class Meta:
        model = TypeTechnic
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={
                'cols': 65, 'rows': 5,
                'class': 'text_article_form'}),
        }


class TechnicForm(forms.ModelForm):
    """ Форма типа техники"""

    class Meta:
        model = Technic
        fields = '__all__'

class ServiceForm(forms.ModelForm):
    """ Форма для тех. Обслуживания"""

    class Meta:
        model = Service
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={
                'cols': 65, 'rows': 5,
                'class': 'text_article_form'})
        }

technic/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.shortcuts import reverse
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, DetailView
from pyexpat.errors import messages

from technic.forms import DepartmentForm, TypeTechnicForm, TechnicForm, ServiceForm
from technic.models import Technic, TypeTechnic, Department, Service
from technic.service import get_info


class TechnicListView(ListView):
    """ Список всей техники."""
    model = Technic
    paginate_by = 6
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': f'Техника'
    }


class TechnicCreateView(CreateView):
    """ Создание техники"""
    model = Technic
    form_class = TechnicForm
    success_url = reverse_lazy('technic:technic_list')
    template_name = 'technic/technic_create.html'
    extra_context = {
        'title': f'Добавление техники'
    }


class TechnicDetailView(DetailView):
    """ Просмотр детальной информации по техники."""
    model = Technic
    template_name = 'technic/technic_detail.html'
    extra_context = {
        'title': f'Детальная информация'
    }


class TechnicUpdateView(UpdateView):
    """ Изменение техники."""
    model = Technic
    form_class = TechnicForm
    template_name = 'technic/technic_update.html'

    def get_success_url(self):
        # Переходим на страницу детальной информации по технике после редактирования
        return reverse('technic:technic_detail', args=[self.kwargs.get('pk')])


class TechnicServiceUpdateView(UpdateView):
    """ Странина сервиса техники"""
    model = Technic
    form_class = TechnicForm
    template_name = 'technic/technic_service_update.html'

    def get_success_url(self):
        # Переходим на страницу детальной информации по технике после редактирования
        return reverse('technic:technic_service_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        # Добавляем форму для редактирования сервисных работ
        contex_data = super().get_context_data(**kwargs)
        ServiceFormset = inlineformset_factory(Technic, Service, form=ServiceForm, extra=1)
        if self.request.method == 'POST':
            formset = ServiceFormset(self.request.POST, instance=self.object)
        else:
            formset = ServiceFormset(instance=self.object)
        contex_data['formset'] = formset
        contex_data['title'] = f'Редактирование техники'
        return contex_data

    def form_valid(self, form):
        # форма валидации для подставления сервиса
        contex_data = self.get_context_data()
        formset = contex_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class TechnicDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления техники."""
    model = Technic
    template_name = 'technic/technic_delete.html'
    success_url = reverse_lazy('technic:technic_list')
    permission_required = 'technic.delete_technic'
    extra_context = {
        'title': f'Удаление техники'
    }


class DepartmentListView(ListView):
    """ Показывает страницу с информацией о техники определенного подразделения"""
    model = Department
    template_name = 'technic/dep_list.html'
    extra_context = {
        'title': f'Отделения'
    }


class TypeListView(ListView):
    """ Показывает страницу с информацией о техники определенного типа"""
    model = TypeTechnic
    template_name = 'technic/type_list.html'
    extra_context = {
        'title': f'Типы техники'
    }


class DepartmentCreateView(CreateView):
    """ Создание подразделения"""
    model = Department
    form_class = DepartmentForm
    success_url = reverse_lazy('technic:department_list')
    template_name = 'technic/dep_create.html'
    extra_context = {
        'title': f'Создание отделения'
    }


class DepartmentUpdateView(UpdateView):
    """ Изменение подразделения"""
    model = Department
    form_class = DepartmentForm
    template_name = 'technic/dep_update.html'
    success_url = reverse_lazy('technic:department_list')
    extra_context = {
        'title': f'Редактирование отделения'
    }


class DepartmentDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления подразделения."""
    model = Department
    template_name = 'technic/dep_delete.html'
    success_url = reverse_lazy('technic:department_list')
    permission_required = 'technic.delete_department'
    extra_context = {
        'title': f'Удаление отделения'
    }


class TypeTechnicCreateView(CreateView):
    """ Создание типа техники"""
    model = TypeTechnic
    form_class = TypeTechnicForm
    success_url = reverse_lazy('technic:type_list')
    template_name = 'technic/type_create.html'
    extra_context = {
        'title': f'Создание типа техники'
    }


class TypeTechnicUpdateView(UpdateView):
    """ Изменение типа техники."""
    model = TypeTechnic
    form_class = TypeTechnicForm
    template_name = 'technic/type_update.html'
    success_url = reverse_lazy('technic:type_list')
    extra_context = {
        'title': f'Редактирование отделения'
    }


class TypeTechnicDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления типа пользователя."""
    model = TypeTechnic
    template_name = 'technic/type_delete.html'
    success_url = reverse_lazy('technic:type_list')
    permission_required = 'technic.delete_typetechnic'
    extra_context = {
        'title': f'Удаление типа техники'
    }


class TechnicListFilterDepartmentView(ListView):
    """ Список всей техники определенного подразделения."""
    model = Technic
    paginate_by = 6
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': f'Техника'
    }

    def get_queryset(self):
        # Фильтр показывает только технику определенного подразделения
        queryset = super().get_queryset().filter(
            department_id=self.kwargs.get('pk')
        )
        return queryset


class TechnicListFilterTypeTechnicView(ListView):
    """ Список всей техники определенного типа."""
    model = Technic
    paginate_by = 6
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': f'Техника'
    }

    def get_queryset(self):
        # Фильтр показывает только технику определенного типа
        queryset = super().get_queryset().filter(
            type_id=self.kwargs.get('pk')
        )
        return queryset


class TechnicSearchListView(LoginRequiredMixin, ListView):
    """ Показывает страницу с результатами поиска техники по гос. Номеру."""
    model = Technic
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': 'Результаты поискового запроса',
    }

    def get_queryset(self):
        query = self.request.GET.get('q')

        object_list = Technic.objects.filter(Q(number__icontains=query))
        if object_list.exists() == False:
            print("Не найден по гос.номеру")
            object_list = Technic.objects.filter(Q(name__icontains=query))
        if object_list.exists() == False:
            print("Не найден по наименованию")
            object_list = Technic.objects.filter(Q(imei__icontains=query))
        if object_list.exists() == False:
            print("Не найден по IMEI")

        print(object_list)
        return object_list


class ServiceFilterTechnicView(ListView):
    """ Список работ проведенных на технике"""
    model = Service
    paginate_by = 6
    template_name = 'technic/service_list.html'

    def get_queryset(self):
        # Фильтр показывает только сервисы с определенным id техники
        queryset = super().get_queryset().filter(
            technic_id=self.kwargs.get('pk')
        )
        return queryset

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        if self.object_list:
            # если список объектов есть, тогда вписываем первый
            contex_data['name_t'] = self.object_list[0].technic
        contex_data['title'] = f'Список работ на технике'
        return contex_data

class TechnicLostDataView(DetailView):
    model = Technic
    template_name = 'technic/technic_glonass_detail.html'

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        num_technic = self.object.number
        glonass_info = get_info(num_technic)
        contex_data['title'] = f'Последние данные от'
        if glonass_info:
            contex_data['glonass_technic'] = glonass_info['glonass_technic']
            contex_data['glonass_data'] = glonass_info['glonass_data']
            contex_data['glonass_address'] = glonass_info['glonass_address']
            contex_data['glonass_speed'] = glonass_info['glonass_speed']
            contex_data['glonass_geozone'] = glonass_info['glonass_geozone']
        return contex_data

technic/templates/technic/base.html
{% load static %}
{% load my_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script async>
        window.onload = function () {
          document.body.classList.add('loaded_hiding');
          window.setTimeout(function () {
            document.body.classList.add('loaded');
            document.body.classList.remove('loaded_hiding');
          }, 500);
        }
      </script>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'image/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/base_page.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">
    <title>C&A: {{ title }}</title>
</head>
<body>
    <div class="preloader">
        <div class="preloader__row">
          <div class="preloader__item"></div>
          <div class="preloader__item"></div>
        </div>
      </div>
<div class="logo">
    <div class="left_logo">
        <img src="{% static 'image/logo.png' %}" alt="Система контроля и учета" style="width: 100%; margin-top: 5px;">
    </div>
    <div class="right_logo">
        <div class="text_logo">
            <div class="user_ava" style="background-image: url({{ request.user.avatar|user_media }})">
            </div>
            <div class="user_data">
                Имя: {{request.user.first_name}}<br>
                E-mail: {{request.user.email}}<br>
            </div>
        </div>
        <div class="menu">
            <div class="navbar">
                <div class="search_box">
                {% include 'technic/includes/inc_search_field.html' %}
                </div>
                <div class="bottom_menu_box">
                <a href="#">Главная</a>
                <a href="{% url 'news:news_list' %}">Новости</a>
                <a href="{% url 'technic:technic_list' %}">Техника</a>
                <div class="dropdown">
                    {% if request.user.role == "admin" or request.user.role == "moderator" %}
                    <button class="dropbtn">Инструменты</button>
                    {% endif %}
                    <div class="dropdown-content">
                        {% if request.user.role == "admin" %}
                        <a href="//localhost:8000/admin_panel/">Админка</a>
                        {% endif %}
                        {% if request.user.role == "admin" or request.user.role == "moderator" %}
                        <a href="{% url 'users:users_list' %}">Пользователи</a>
                        <a href="{% url 'users:create_user' %}">Добавить<br>пользователя</a>
                        {% endif %}
                        <a href="{% url 'technic:department_list' %}">Отделения</a>
                        <a href="{% url 'technic:type_list' %}">Тип техники</a>
                    </div>
                </div>
                <div class="dropdown">
                    <button class="dropbtn2">Настройка</button>
                    <div class="dropdown-content2">
                        <a href="{% url 'users:profile_user' %}">Профиль</a>
                        <a href="{% url 'users:change_password_user' %}">Пароль</a>
                    </div>
                </div>
                <a href="{% url 'users:logout_user' %}" class="exitbtn" >Выход</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="conteiner">
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <div align="center">
            &#9733; This is my private "PET-project". Welcome my <a href="https://github.com/Zheldakov" target="_blank">github</a>
            page.
        </div>
    </div>
</div>

</body>
</html>

technic/templates/technic/dep_delete.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                Вы хотите удалить подразделение: {{ object.name}}
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Удаление</button>
                <a href="{% url 'technic:department_list'%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

technic/templates/technic/dep_list.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    {% if request.user.role == "admin" or request.user.role == "moderator" %}
     <a href="{% url "technic:department_create" %}" class="btn_list btn_list_high">Создать "Отделение"</a>
    {% endif %}
     <div class="conteiner_list">
        {% for object in object_list %}
        {% include 'technic/includes/inc_dep_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'users/includes/inc_pagination.html' %}
</div>
{% endblock %}

technic/templates/technic/dep_type_list.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="conteiner_list">
        {% for object in object_list %}
        {% include 'technic/includes/inc_dep_type_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'users/includes/inc_pagination.html' %}
</div>
{% endblock %}

technic/templates/technic/dep_update.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'technic:department_list'%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

technic/templates/technic/service_list.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
  {% if name_t %}
  <div class="header_form">{{ title }} {{ name_t }}</div>
  {% else %}
  <div class="header_form">Работы не проводились</div>
  {% endif %}
    <div class="top_bottom_list">
      {% if name_t %}
      <button onclick="window.history.back(); return false;" class="btn_esc">Назад</button>
      {% endif %}
    </div>
    <div class="conteiner_list_technic">
        {% for object in object_list %}
        {% include 'technic/includes/inc_service_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'users/includes/inc_pagination.html' %}
    <div class="top_bottom_list">
      <button onclick="window.history.back(); return false;" class="btn_esc">Назад</button>
    </div>
</div>
{% endblock %}

technic/templates/technic/technic_create.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'technic:technic_list' %}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

technic/templates/technic/technic_delete.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                Вы хотите удалить: {{ object.name}}
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Удаление</button>
                <a href="{% url 'technic:technic_detail' object.pk%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

technic/templates/technic/technic_detail.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }} {{ object }}</div>
    <div class="body_form">
    <div class="form_form_profile">
        <div class="image_form" style="background-image: url({{ technic.photo|technic_media }})">
        </div>
    </div>
    <div class="user_text">
        <span><div class="label_user">Наименование:</div> <div>{{object.name}}</div></span>
        <span><div class="label_user">Гос.номер:</div> <div>{{object.number|default:"не указано"}}</div></span>
        <span><div class="label_user">Тип:</div> <div>{{object.type}}</div></span>
        <span><div class="label_user">Инв.номер</div> <div>{{object.invnumber|default:"не указано"}}</div></span>
        <span><div class="label_user">IMEI:</div> <div>{{object.imei|default:"не указано"}}</div></span>
        <span><div class="label_user">Подразделение:</div> <div>{{object.department|default:"не указано"}}</div></span>
    </div>
    <div class="button_form">
        <a class="btn_list btn_technic" href="{% url 'technic:technic_service_update' object.pk %}">Сервис</a>
        <a href="{% url 'technic:technic_update' object.pk %}" class="btn_enter">Редактировать</a>
        {% if request.user.role == "admin" or request.user.role == "moderator" %}
        <a href="{% url 'technic:technic_delete' object.pk%}" class="btn_esc">Удалить</a>
        {% endif %}
        <a href="{% url 'technic:technic_list' %}" class="btn_enter">Назад</a>
    </div>
</div>
</div>
{% endblock %}

technic/templates/technic/technic_glonass_detail.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="content_form">
        <div class="header_form">{{ title }} {{ object }}</div>
        <div class="body_form">
            <div class="form_form_profile">
                <div class="image_form" style="background-image: url({{ technic.photo|technic_media }})">
                </div>
            </div>
            <div class="user_text">
                <span><div class="label_user">Наименование:</div> <div>{{ object.name }}</div></span>
                <span><div class="label_user">Гос.номер:</div> <div>{{ object.number|default:"не указано" }}</div></span>
                {% if glonass_technic %}
                    <span><div class="label_user">Дата и время::</div> <div>{{ glonass_data }}</div></span>
                    <span><div class="label_user">Адрес:</div> <div>{{ glonass_address }}</div></span>
                    <span><div class="label_user">Скорость:</div> <div>{{ glonass_speed }}</div></span>
                    {% if glonass_geozone %}
                        <span><div class="label_user">Номер поле:</div> <div>{{ glonass_geozone }}</div></span>
                    {% endif %}
                {% else %}
                    <div style="color: red; width:100%; text-align: center;margin-bottom: 5px;">Данные о местонахождении
                        отсутствуют
                    </div>
                {% endif %}
            </div>
            <div class="button_form">
                <a href="{% url 'technic:technic_list' %}" class="btn_enter">Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

technic/templates/technic/technic_list.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="top_bottom_list">
        <a href="{% url "technic:technic_create" %}" class="btn_list btn_list_high">Добавить Технику</a>
        <a href="{% url 'technic:department_list' %}" class="btn_list btn_list_high">Отделения</a>
        <a href="{% url 'technic:type_list' %}" class="btn_list btn_list_high">Типы техники</a>
    </div>
    <div class="conteiner_list_technic">
        {% for object in object_list %}
        {% include 'technic/includes/inc_technic_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'users/includes/inc_pagination.html' %}
</div>
{% endblock %}

technic/templates/technic/type_create.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Сохранить</button>
                <a href="{% url 'technic:type_list' %}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

technic/templates/technic/type_delete.html
{% extends 'technic/base.html' %}
{% block content %}
<div class="content_form">
    <div class="header_form">{{ title }}</div>
    <div class="body_form">
        <form method="post" enctype="multipart/form-data">
            <div class="form_form">
                Вы хотите удалить тип техники: {{ object.name}}
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="button_form">
                <button type="submit" class="btn_enter">Удаление</button>
                <a href="{% url 'technic:type_list'%}" class="btn_esc">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

technic/templates/technic/type_list.html
{% extends 'technic/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    {% if request.user.role == "admin" or request.user.role == "moderator" %}
    <a href="{% url "technic:type_create" %}" class="btn_list btn_list_high">Создать "Тип техники"</a>
    {% endif %}
    <div class="conteiner_list">
        {% for object in object_list %}
        {% include 'technic/includes/inc_type_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'users/includes/inc_pagination.html' %}
</div>
{% endblock %}