config/urls.py
"""
Настройка URL-адресов для проекта config.

Список `urlpatterns` перенаправляет URL-адреса в представления. Для получения дополнительной информации, пожалуйста, смотрите:
 https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
 1. Добавьте импорт: из my_app импортируйте представления
 2. Добавьте URL-адрес в urlpatterns: path(", views.home, name="home")
Представления на основе классов
 1. Добавьте импорт: из other_app.views импортируйте Home
 2. Добавьте URL-адрес в urlpatterns: path(", Home.as_view(), name="home")
Включая другой URLconf
 1. Импортируйте функцию include(): из django.urls импортируйте include, path
 2. Добавьте URL-адрес в urlpatterns: path('blog/', include('blog.urls'))
"""
"""Отслеживание url-адресов"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# urls для административной панели Django
urlpatterns = [
                  path('admin_panel/', admin.site.urls),  # URL для административной панели Django
                  path('', include('users.urls', namespace='users')),  # URL для приложения users
                  path('technic/', include('technic.urls', namespace='technic')), # URL для приложения technic
                  path('news/', include('news.urls', namespace='news')), # URL для приложения news
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавляем медиафайлы

news/urls.py
from django.urls import path

from news.apps import NewsConfig
from news.views import NewsListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = NewsConfig.name

urlpatterns = [
    path('', NewsListView.as_view(), name="news_list"),  # список всех новостей
    path('<int:pk>',ArticleDetailView.as_view(), name="news_detail"), # статья
    path('create/',ArticleCreateView.as_view(), name="news_create"), # создание статьи
    path('update/<int:pk>/',ArticleUpdateView.as_view(), name="news_update"), # редактирование статьи
    path('delete/<int:pk>',ArticleDeleteView.as_view(), name="news_delete"), # удаление статьи
]

technic/urls.py
from django.urls import path

from technic.apps import TechnicConfig
from technic.views import TechnicListView, DepartmentListView, TypeListView, TypeTechnicUpdateView, \
    DepartmentUpdateView, TypeTechnicDeleteView, DepartmentDeleteView, DepartmentCreateView, TypeTechnicCreateView, \
    TechnicDetailView, TechnicUpdateView, TechnicDeleteView, TechnicCreateView, TechnicListFilterDepartmentView, \
    TechnicListFilterTypeTechnicView, TechnicSearchListView, TechnicServiceUpdateView, ServiceFilterTechnicView, \
    TechnicLostDataView

app_name = TechnicConfig.name

urlpatterns = [
    path('list/', TechnicListView.as_view(), name="technic_list"),  # список всей техники
    path('department/<int:pk>/technic/', TechnicListFilterDepartmentView.as_view(), name='department_technic'), # техника определенного подразделения
    path('type/<int:pk>/technic/', TechnicListFilterTypeTechnicView.as_view(), name='type_technic'), # техника определенного типа
    path('create/', TechnicCreateView.as_view(), name="technic_create"),  # добавление техники
    path('detail/<int:pk>/', TechnicDetailView.as_view(), name="technic_detail"),  # детальная информация по техники
    path('update/<int:pk>/', TechnicUpdateView.as_view(), name="technic_update"),  # редактирование техники
    path('delete/<int:pk>/', TechnicDeleteView.as_view(), name="technic_delete"),  # удаление техники
    path('type/', TypeListView.as_view(), name="type_list"),  # список всех типов техники
    path('department/', DepartmentListView.as_view(), name="department_list"),  # список всех подразделений
    path('type/create/', TypeTechnicCreateView.as_view(), name='type_create'), # создание типов техники
    path('department/create/', DepartmentCreateView.as_view(), name='department_create'), # создание подразделений
    path('type/update/<int:pk>/', TypeTechnicUpdateView.as_view(), name='type_update'), # редактирование типа техники
    path('department/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'), # редактирование подразделений
    path('type/delete/<int:pk>/', TypeTechnicDeleteView.as_view(), name='type_delete'), # удаление типа техники
    path('department/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'), # удаление подразделений
    path('number/search/', TechnicSearchListView.as_view(), name='technic_search'), # поиск техники по гос номеру
    path('service/<int:pk>/', TechnicServiceUpdateView.as_view(), name='technic_service_update'), # сервис техники
    path('<int:pk>/service/', ServiceFilterTechnicView.as_view(), name='technic_service_list'), # список сервисов по техники
    path('<int:pk>/lost_data/', TechnicLostDataView.as_view(), name='technic_lost_data'), # последние данные от техники
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_login_view, user_logout_view, UserUpdateView, UserPasswordChangeView, UserProfileView, \
    UserListView, AllUserProfileView, ALLUserUpdateView, UserDeleteView, UserCreateView

app_name = UsersConfig.name

urlpatterns = [
    path('', user_login_view, name="login_user"), #  url стартовой страницы для входа
    path('logout/', user_logout_view, name="logout_user"),
    path('profile/', UserProfileView.as_view(), name='profile_user'),
    path('update/', UserUpdateView.as_view(), name="update_user"),
    path('change_password/', UserPasswordChangeView.as_view(), name='change_password_user'),

# просмотр других пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('create/', UserCreateView.as_view(), name='create_user'),
    path('profile/<int:pk>/', AllUserProfileView.as_view(), name='profile_all_user'),
    path('update/<int:pk>/', ALLUserUpdateView.as_view(), name='update_all_user'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='delete_user'),
]

technic/forms.py
from django import forms
from .models import Department, TypeTechnic, Technic, Service


class DepartmentForm(forms.ModelForm):
    """ Форма подразделения."""

    class Meta:
        model = Department
        fields = '__all__'

        widgets = {
            'description': forms.Textarea(attrs={
                'cols': 65, 'rows': 5,
                'class': 'text_article_form'}),
        }


class TypeTechnicForm(forms.ModelForm):
    """ Форма типа техники"""

    class Meta:
        model = TypeTechnic
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={
                'cols': 65, 'rows': 5,
                'class': 'text_article_form'}),
        }


class TechnicForm(forms.ModelForm):
    """ Форма типа техники"""

    class Meta:
        model = Technic
        fields = '__all__'

class ServiceForm(forms.ModelForm):
    """ Форма для тех. Обслуживания"""

    class Meta:
        model = Service
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={
                'cols': 65, 'rows': 5,
                'class': 'text_article_form'})
        }

technic/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.shortcuts import reverse
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, DetailView
from pyexpat.errors import messages

from technic.forms import DepartmentForm, TypeTechnicForm, TechnicForm, ServiceForm
from technic.models import Technic, TypeTechnic, Department, Service
from technic.service import get_info


class TechnicListView(ListView):
    """ Список всей техники."""
    model = Technic
    paginate_by = 6
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': f'Техника'
    }


class TechnicCreateView(CreateView):
    """ Создание техники"""
    model = Technic
    form_class = TechnicForm
    success_url = reverse_lazy('technic:technic_list')
    template_name = 'technic/technic_create.html'
    extra_context = {
        'title': f'Добавление техники'
    }


class TechnicDetailView(DetailView):
    """ Просмотр детальной информации по техники."""
    model = Technic
    template_name = 'technic/technic_detail.html'
    extra_context = {
        'title': f'Детальная информация'
    }


class TechnicUpdateView(UpdateView):
    """ Изменение техники."""
    model = Technic
    form_class = TechnicForm
    template_name = 'technic/technic_update.html'

    def get_success_url(self):
        # Переходим на страницу детальной информации по технике после редактирования
        return reverse('technic:technic_detail', args=[self.kwargs.get('pk')])


class TechnicServiceUpdateView(UpdateView):
    """ Странина сервиса техники"""
    model = Technic
    form_class = TechnicForm
    template_name = 'technic/technic_service_update.html'

    def get_success_url(self):
        # Переходим на страницу детальной информации по технике после редактирования
        return reverse('technic:technic_service_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        # Добавляем форму для редактирования сервисных работ
        contex_data = super().get_context_data(**kwargs)
        ServiceFormset = inlineformset_factory(Technic, Service, form=ServiceForm, extra=1)
        if self.request.method == 'POST':
            formset = ServiceFormset(self.request.POST, instance=self.object)
        else:
            formset = ServiceFormset(instance=self.object)
        contex_data['formset'] = formset
        contex_data['title'] = f'Редактирование техники'
        return contex_data

    def form_valid(self, form):
        # форма валидации для подставления сервиса
        contex_data = self.get_context_data()
        formset = contex_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class TechnicDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления техники."""
    model = Technic
    template_name = 'technic/technic_delete.html'
    success_url = reverse_lazy('technic:technic_list')
    permission_required = 'technic.delete_technic'
    extra_context = {
        'title': f'Удаление техники'
    }


class DepartmentListView(ListView):
    """ Показывает страницу с информацией о техники определенного подразделения"""
    model = Department
    template_name = 'technic/dep_list.html'
    extra_context = {
        'title': f'Отделения'
    }


class TypeListView(ListView):
    """ Показывает страницу с информацией о техники определенного типа"""
    model = TypeTechnic
    template_name = 'technic/type_list.html'
    extra_context = {
        'title': f'Типы техники'
    }


class DepartmentCreateView(CreateView):
    """ Создание подразделения"""
    model = Department
    form_class = DepartmentForm
    success_url = reverse_lazy('technic:department_list')
    template_name = 'technic/dep_create.html'
    extra_context = {
        'title': f'Создание отделения'
    }


class DepartmentUpdateView(UpdateView):
    """ Изменение подразделения"""
    model = Department
    form_class = DepartmentForm
    template_name = 'technic/dep_update.html'
    success_url = reverse_lazy('technic:department_list')
    extra_context = {
        'title': f'Редактирование отделения'
    }


class DepartmentDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления подразделения."""
    model = Department
    template_name = 'technic/dep_delete.html'
    success_url = reverse_lazy('technic:department_list')
    permission_required = 'technic.delete_department'
    extra_context = {
        'title': f'Удаление отделения'
    }


class TypeTechnicCreateView(CreateView):
    """ Создание типа техники"""
    model = TypeTechnic
    form_class = TypeTechnicForm
    success_url = reverse_lazy('technic:type_list')
    template_name = 'technic/type_create.html'
    extra_context = {
        'title': f'Создание типа техники'
    }


class TypeTechnicUpdateView(UpdateView):
    """ Изменение типа техники."""
    model = TypeTechnic
    form_class = TypeTechnicForm
    template_name = 'technic/type_update.html'
    success_url = reverse_lazy('technic:type_list')
    extra_context = {
        'title': f'Редактирование отделения'
    }


class TypeTechnicDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления типа пользователя."""
    model = TypeTechnic
    template_name = 'technic/type_delete.html'
    success_url = reverse_lazy('technic:type_list')
    permission_required = 'technic.delete_typetechnic'
    extra_context = {
        'title': f'Удаление типа техники'
    }


class TechnicListFilterDepartmentView(ListView):
    """ Список всей техники определенного подразделения."""
    model = Technic
    paginate_by = 6
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': f'Техника'
    }

    def get_queryset(self):
        # Фильтр показывает только технику определенного подразделения
        queryset = super().get_queryset().filter(
            department_id=self.kwargs.get('pk')
        )
        return queryset


class TechnicListFilterTypeTechnicView(ListView):
    """ Список всей техники определенного типа."""
    model = Technic
    paginate_by = 6
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': f'Техника'
    }

    def get_queryset(self):
        # Фильтр показывает только технику определенного типа
        queryset = super().get_queryset().filter(
            type_id=self.kwargs.get('pk')
        )
        return queryset


class TechnicSearchListView(LoginRequiredMixin, ListView):
    """ Показывает страницу с результатами поиска техники по гос. Номеру."""
    model = Technic
    template_name = 'technic/technic_list.html'
    extra_context = {
        'title': 'Результаты поискового запроса',
    }

    def get_queryset(self):
        query = self.request.GET.get('q')

        object_list = Technic.objects.filter(Q(number__icontains=query))
        if object_list.exists() == False:
            print("Не найден по гос.номеру")
            object_list = Technic.objects.filter(Q(name__icontains=query))
        if object_list.exists() == False:
            print("Не найден по наименованию")
            object_list = Technic.objects.filter(Q(imei__icontains=query))
        if object_list.exists() == False:
            print("Не найден по IMEI")

        print(object_list)
        return object_list


class ServiceFilterTechnicView(ListView):
    """ Список работ проведенных на технике"""
    model = Service
    paginate_by = 6
    template_name = 'technic/service_list.html'

    def get_queryset(self):
        # Фильтр показывает только сервисы с определенным id техники
        queryset = super().get_queryset().filter(
            technic_id=self.kwargs.get('pk')
        )
        return queryset

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        if self.object_list:
            # если список объектов есть, тогда вписываем первый
            contex_data['name_t'] = self.object_list[0].technic
        contex_data['title'] = f'Список работ на технике'
        return contex_data

class TechnicLostDataView(DetailView):
    model = Technic
    template_name = 'technic/technic_glonass_detail.html'

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        num_technic = self.object.number
        glonass_info = get_info(num_technic)
        contex_data['title'] = f'Последние данные от'
        if glonass_info:
            contex_data['glonass_technic'] = glonass_info['glonass_technic']
            contex_data['glonass_data'] = glonass_info['glonass_data']
            contex_data['glonass_address'] = glonass_info['glonass_address']
            contex_data['glonass_speed'] = glonass_info['glonass_speed']
            contex_data['glonass_geozone'] = glonass_info['glonass_geozone']
        return contex_data

technic/templates/technic/includes/inc_dep_card.html
{% load my_tags %}
<div class="block_list_dt">
    
        <ul class="ul_list_dt">
            <li><span style="font-weight: bold;font-size: larger;"> {{ object.name }}</span></li>
            <li><span style="font-weight: bold;">Описание:</span> {{ object.description}}</li>
        </ul>
        <div class ="btn_block_dt">
        <a class="btn_list" href="{% url 'technic:department_technic' object.pk %}">Техника</a>
        {% if request.user.role == "admin" or request.user.role == "moderator" %}
        <a class="btn_list" href="{% url 'technic:department_update' object.pk %}">Редактирование</a>
        <a class="btn_list_delete" href="{% url 'technic:department_delete' object.pk %}">Удаление</a>
        {% endif %}
        {% if object.is_active == False %}
        <span style="color: red; text-align: center;">Не активен</span>
        {% endif %}
        </div>
</div>

technic/templates/technic/includes/inc_dep_type_card.html
{% load my_tags %}
<div class="block_list_dt">
    
        <ul class="ul_list_dt">
            <li><span style="font-weight: bold;font-size: larger;"> {{ object.name }}</span></li>
            <li><span style="font-weight: bold;">Описание:</span> {{ object.description}}</li>
        </ul>
        <div class ="btn_block_dt">
        <a class="btn_list" href="{% url 'users:profile_all_user' object.pk %}">Редактирование</a>
        {% if request.user.role == "admin" or request.user.role == "moderator" %}
        <a class="btn_list_delete" href="{% url 'users:delete_user' object.pk %}">Удаление</a>
        {% endif %}
        {% if object.is_active == False %}
        <span style="color: red; text-align: center;">Не активен</span>
        {% endif %}
        </div>
</div>

technic/templates/technic/includes/inc_search_field.html
<form action="{% url 'technic:technic_search' %}" method="get">
    <input name="q" type="text" placeholder="Поиск техники"><button type="submit">&#128269;</button>
</form>

technic/templates/technic/includes/inc_service_card.html
{% load my_tags %}
<div class="block_list_technic">
    <div class="image_list_block_technic" style="background-image: url({{  object.photo|service_media }})">
    </div>
    <div class="line_block_technic">
        <div class="serv_block_technic_left">
            <span style="font-weight: bold;font-size: larger;"> {{ object.work }}</span>
            <span>Дата: {{ object.date}}</span>
        </div>
        <div class="serv_block_technic_right">
            <div class="text_block_technic_top">
                <span>Описание: {{ object.description}}</span>
            </div>
        </div>
    </div>
</div>

technic/templates/technic/includes/inc_technic_card.html
{% load my_tags %}
<div class="block_list_technic">
    <div class="image_list_block_technic" style="background-image: url({{ object.photo|technic_media }})">
    </div>
    <div class="line_block_technic">
        <div class="block_data_technic">
            <span style="font-weight: bold;font-size: larger;"> {{ object.name }}</span>
            <span>Гос.№:{{ object.number}}</span>
        </div>

        <div class="block_data_technic" style="padding: 0;">


            <div class="text_block_technic_top">
                <span>Отделение: {{ object.department}}</span>
                <span>Тип: {{ object.type}}</span>
            </div>


            <div class="btn_block_technic">
                <a class="btn_list btn_technic" href="{% url 'technic:technic_service_list' object.pk %}">Сервис</a>
                <a class="btn_list btn_technic" href="{% url 'technic:technic_detail' object.pk %}">Подробнее</a>
                 <a title="Местоположение" class="btn_list btn_technic_glonass" href="{% url 'technic:technic_lost_data' object.pk %}">&#9873;</a>
            </div>
        </div>
        {% if object.is_active == False %}
        <span style="color: red; text-align: center;">Не активен</span>
        {% endif %}
    </div>
</div>

technic/templates/technic/includes/inc_tecnhnic_card.html
{% load my_tags %}
<div class="block_list_technic">
    <div class="image_list_block_technic" style="background-image: url({{ object.photo|technic_media }})">
    </div>
    <div class="line_block_technic">
        <div class="block_data_technic">
            <span style="font-weight: bold;font-size: larger;"> {{ object.name }}</span>
            <span>Гос.№:{{ object.number}}</span>
        </div>

        <div class="block_data_technic" style="padding: 0;">
            
           
                <div class="text_block_technic_top">
                    <span>Отделение: {{ object.department}}</span>
                    <span>Тип: {{ object.type}}</span> 
                </div>

            
            <div class="btn_block_technic">
                <a class="btn_list btn_technic" href="{% url 'technic:technic_detail' object.pk %}">Подробнее</a>
            </div>
        </div>
        {% if object.is_active == False %}
        <span style="color: red; text-align: center;">Не активен</span>
        {% endif %}
    </div>
</div>

technic/templates/technic/includes/inc_type_card.html
{% load my_tags %}
<div class="block_list_dt">
    
        <ul class="ul_list_dt">
            <li><span style="font-weight: bold;font-size: larger;"> {{ object.name }}</span></li>
            <li><span style="font-weight: bold;">Описание:</span> {{ object.description}}</li>
        </ul>
        <div class ="btn_block_dt">
        <a class="btn_list" href="{% url 'technic:type_technic' object.pk %}">Техника</a>
        {% if request.user.role == "admin" or request.user.role == "moderator" %}
        <a class="btn_list" href="{% url 'technic:type_update' object.pk %}">Редактирование</a>
        <a class="btn_list_delete" href="{% url 'technic:type_delete' object.pk %}">Удаление</a>
        {% endif %}
        {% if object.is_active == False %}
        <span style="color: red; text-align: center;">Не активен</span>
        {% endif %}
        </div>
</div>